GET http://localhost:3003/api/blogs


###
POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1vYWQiLCJpZCI6IjY1ZTYyNzg4OWRiZDIyZGM4ZTVmZmZlNiIsImlhdCI6MTcxMDg5MDAxNX0.cvEVNSAlmjM2hESonZaIwFqs00p106Fq2jriNUxDUTg

{
    "title": "moad's story",
    "author": "moad",
    "url": "http://moad.com/"
}